/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CourseMarketplaceContract } from "./CourseMarketplace";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CourseMarketplace"): CourseMarketplaceContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export {
  CourseMarketplaceContract,
  CourseMarketplaceInstance,
} from "./CourseMarketplace";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
